cargo-features = ["edition2024"]

[package]
name = "tsdistances"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[build-dependencies]
spirv-builder = { git = "https://github.com/Rust-GPU/rust-gpu.git", version = "0.9.0" }

[profile.release.build-override]
opt-level = 3
codegen-units = 16

[profile.dev.build-override]
opt-level = 3

[dependencies]
vulkano = { version = "0.35.1", optional = true }
spirv-std = { version = "0.9", optional = true }


[features]
default = ["dep:spirv-std"]
build_cpu = ["dep:vulkano"]
